apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i32v6e066-dotnet-basic
  janus-idp.io/tekton: i32v6e066-dotnet-basic
  backstage.io/kubernetes-id: i32v6e066-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i32v6e066-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
